INSERT ALL
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(1, to_date('01-07-2026', 'dd-mm-yyyy'), 300, 'EUR')
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(2, to_date('02-07-2026', 'dd-mm-yyyy'), 200, 'EUR')
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(3, to_date('03-07-2026', 'dd-mm-yyyy'), 100, 'DOL')
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(4, to_date('04-07-2026', 'dd-mm-yyyy'), 400, 'EUR')
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(5, to_date('05-07-2026', 'dd-mm-yyyy'), 233, 'DOL')
  INTO SB_INVOICES (INVOICE_ID, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY) values(6, to_date('06-07-2026', 'dd-mm-yyyy'), 300, 'EUR')
SELECT * FROM dual;

INSERT ALL
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (1, to_date('01-07-2026', 'dd-mm-yyyy'), 150, 'EUR', 1);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (2, to_date('02-07-2026', 'dd-mm-yyyy'), 150, 'EUR', 1);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (3, to_date('03-07-2026', 'dd-mm-yyyy'), 40, 'EUR', 2);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (4, to_date('04-07-2026', 'dd-mm-yyyy'), 40, 'EUR', 2);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (5, to_date('05-07-2026', 'dd-mm-yyyy'), 100, 'DOL', 3);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (6, to_date('06-07-2026', 'dd-mm-yyyy'), 20, 'EUR', 4);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (7, to_date('07-07-2026', 'dd-mm-yyyy'), 20, 'EUR', 4);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (8, to_date('08-07-2026', 'dd-mm-yyyy'), 20, 'EUR', 4);
  into SB_PAYMENTS (PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, CURRENCY, INVOICE_ID) values (9, to_date('09-07-2026', 'dd-mm-yyyy'), 66, 'DOL', 5)
select * from dual;
